version: '3.7'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'example'
    ports:
      - 15555:5432

